### ISSUE TITLE
OpenGL context error while running usdrecord in headless mode

### ISSUE THREAD

**Issue by rajdhandus** [PixarAnimationStudios/OpenUSD#2061]
### Description of Issue
Not able to run usdrecord in headless mode.

Traceback (most recent call last):
  File "/usr/local/nvidia/usd/bin/usdrecord", line 168, in <module>
    sys.exit(main())
  File "/usr/local/nvidia/usd/bin/usdrecord", line 140, in main
    frameRecorder = UsdAppUtils.FrameRecorder()
pxr.Tf.ErrorException:
	Error in 'pxrInternal_v0_21__pxrReserved__::GlfContextCaps::_LoadCaps' at line 162 in file /buildAgent/work/ca6c508eae419cf8/USD/pxr/imaging/glf/contextCaps.cpp : 'Failed verification: ' GlfGLContext::GetCurrentGLContext()->IsValid() ''
	Error in 'pxrInternal_v0_21__pxrReserved__::{anonymous}::_IsHydraEnabled' at line 109 in file /buildAgent/work/ca6c508eae419cf8/USD/pxr/usdImaging/usdImagingGL/engine.cpp : 'OpenGL context required, using reference renderer'
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.6/dist-packages/PySide2/Qt/plugins/platforms/libqoffscreen.so"

### Steps to Reproduce

Run https://github.com/Ewpratten/docker-usd/blob/master/Dockerfile 

### System Information (OS, Hardware)
ubuntu20.04
x86_64 x86_64 x86_64 GNU/Linux

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:3E:00.0 Off |                    0 |
| N/A   43C    P0    45W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

### Package Versions
Python 3.6.15
PySide2 5.15.2.1
PyOpenGL 3.1.6
usd-21-05
opt-qt-5.15.2-focal

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7708

**Comment by FlorianZ** [comment]
@rajdhandus I see your docker file is pulling in a USD from NVIDIA's repository. Have you tried this with a recent official version of USD. We think this may be fixed already. Might be worth waiting until 23.02 lands before trying to repro this. It will take us a while to get back to this internally, but let us know if you're still seeing this issue in a recent version.

**Comment by beersandrew** [comment]
@FlorianZ I was able to reproduce this issue with USD version 22.08 on RHEL, and I was able to confirm it works with USD version 23.08 on RHEL

**Comment by blevin** [comment]
Closing as confirmed fixed as of 23.08.
