### ISSUE TITLE
Fatal Errors do not abort cleanly

### ISSUE THREAD

**Issue by aloysbaillet** [PixarAnimationStudios/OpenUSD#86]
### System Information (OS, Hardware, etc.)

linux CentOS 6.6
### Package Versions

```
all standard
```
### Build Flags

```
all standard
```
### Steps to Reproduce
1. Write a simple code that dereferences an invalid TfRefPtr pointer
2. You will get the following stack trace in GDB, with the SIGTRAP not being caught by normal signal handlers:

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007f1de4181aca in ArchDebuggerTrap() () from usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/lib/python/pxr/Usd/../../../libarch.so
(gdb) bt
#0  0x00007f1de4181aca in ArchDebuggerTrap() () from usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/lib/python/pxr/Usd/../../../libarch.so
#1  0x00007f1de41862f2 in ArchLogPostMortem(char const_, char const_) () from usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/lib/python/pxr/Usd/../../../libarch.so
#2  0x00007f1de4a7c9c1 in TfLogCrash(std::string const&, std::string const&, std::string const&, TfCallContext const&, bool) ()

   from usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/lib/python/pxr/Usd/../../../libtf.so
#3  0x00007f1de4a24f44 in TfDiagnosticMgr::PostFatal(TfCallContext const&, TfEnum, std::string const&) const ()

   from usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/lib/python/pxr/Usd/../../../libtf.so
#4  0x00007f1de4a1e2f8 in Tf_DiagnosticHelper::IssueFatalError(char const*, ...) const () from usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/lib/python/pxr/Usd/../../../libtf.so
#5  0x00007f1d99f7bacb in TfRefPtr<UsdStage>::operator-> (this=0x1620efe0) at usdCore/0.9.0.10/AL_boost-1.55/AL_boost_python-1.55/include/pxr/base/tf/refPtr.h:893

This means that these fatal errors are currently not being handled properly by our own crash reporting system.

Reading the source it seems that the ArchLogPostMortem function is somehow deciding to call the ArchDebuggerTrap function at this line:
 https://github.com/PixarAnimationStudios/USD/blob/e6ce9e884a65e7d6acd762e9dbc961dcf9aa36bb/pxr/base/lib/arch/stackTrace.cpp#L845
Which seems to be caused by this function Arch_DebuggerIsAttachedPosix returning true?
But I don't think it should...

As mentioned by Alex Mohr in this post https://groups.google.com/d/msg/usd-interest/l_EgFgSLYH8/S1oOTAzIAgAJ the PostFatal should just call std::abort() and let the process terminate.

Cheers,

Aloys

**Comment by jtran56** [comment]
Filed as internal issue #138889.

**Comment by nvmkuruc** [comment]
@aloysbaillet This might be fixed by @pmolodo 's recent PR #3014.

**Comment by jesschimein** [comment]
Closing this issue for now since #3014 has been merged.  Feel free to re-open if needed!
